<?php

return [
    'show_warnings' => false,
    'public_path' => public_path(),
    'convert_entities' => true,
    'options' => [
        'font_dir' => storage_path('fonts/'),
        'font_cache' => storage_path('fonts/'),
        'temp_dir' => sys_get_temp_dir(),
        'chroot' => public_path(),
        'enable_font_subsetting' => true,
        'pdf_backend' => 'CPDF',
        'default_media_type' => 'print',
        'default_paper_size' => 'a4',
        'default_font' => 'DejaVu Sans',
        'dpi' => 150,
        'enable_php' => true,
        'enable_javascript' => false,
        'enable_remote' => true,
        'font_height_ratio' => 1.1,
        'enable_html5_parser' => true,
        'is_remote_enabled' => true,
        'is_html5_parser_enabled' => true,
        'is_php_enabled' => true,
        'is_javascript_enabled' => false,
        'is_font_subsetting_enabled' => true,
        'font_cache' => true,
        'log_output_file' => storage_path('logs/dompdf.log'),
    ],
];